[package]
name = "basalt-protos"
version = "0.1.0"
edition = "2021"

[features]
server = []
client = []
all = ["server", "client"]

[dependencies]
prost = "0.13.4"
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
