/**
 * @fileoverview gRPC-Web generated client stub for basalt
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: basalt.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as basalt_pb from './basalt_pb'; // proto import: "basalt.proto"


export class AuthClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorlogin = new grpcWeb.MethodDescriptor(
    '/basalt.Auth/login',
    grpcWeb.MethodType.UNARY,
    basalt_pb.LoginRequest,
    basalt_pb.LoginResponse,
    (request: basalt_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    basalt_pb.LoginResponse.deserializeBinary
  );

  login(
    request: basalt_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<basalt_pb.LoginResponse>;

  login(
    request: basalt_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: basalt_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<basalt_pb.LoginResponse>;

  login(
    request: basalt_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: basalt_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/basalt.Auth/login',
        request,
        metadata || {},
        this.methodDescriptorlogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/basalt.Auth/login',
    request,
    metadata || {},
    this.methodDescriptorlogin);
  }

}

