"use strict";
// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file basalt.proto (package basalt, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.Auth = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service basalt.Auth
 */
exports.Auth = {
    typeName: "basalt.Auth",
    methods: {
        /**
         * @generated from rpc basalt.Auth.login
         */
        login: {
            name: "login",
            I: basalt_pb_js_1.LoginRequest,
            O: basalt_pb_js_1.LoginResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
//# sourceMappingURL=basalt_connect.js.map