"use strict";
// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file basalt.proto (package basalt, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Auth = exports.LoginResponseSchema = exports.LoginRequestSchema = exports.file_basalt = void 0;
const codegenv1_1 = require("@bufbuild/protobuf/codegenv1");
/**
 * Describes the file basalt.proto.
 */
exports.file_basalt = (0, codegenv1_1.fileDesc)("CgxiYXNhbHQucHJvdG8SBmJhc2FsdCIuCgxMb2dpblJlcXVlc3QSDAoEbmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIlCg1Mb2dpblJlc3BvbnNlEhQKDHNlc3Npb25Ub2tlbhgBIAEoCTI8CgRBdXRoEjQKBWxvZ2luEhQuYmFzYWx0LkxvZ2luUmVxdWVzdBoVLmJhc2FsdC5Mb2dpblJlc3BvbnNlQlEKCmNvbS5iYXNhbHRCC0Jhc2FsdFByb3RvUAGiAgNCWFiqAgZCYXNhbHTKAgZCYXNhbHTiAhJCYXNhbHRcR1BCTWV0YWRhdGHqAgZCYXNhbHRiBnByb3RvMw");
/**
 * Describes the message basalt.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
exports.LoginRequestSchema = (0, codegenv1_1.messageDesc)(exports.file_basalt, 0);
/**
 * Describes the message basalt.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
exports.LoginResponseSchema = (0, codegenv1_1.messageDesc)(exports.file_basalt, 1);
/**
 * @generated from service basalt.Auth
 */
exports.Auth = (0, codegenv1_1.serviceDesc)(exports.file_basalt, 0);
//# sourceMappingURL=basalt_pb.js.map