// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file basalt.proto (package basalt, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file basalt.proto.
 */
export const file_basalt: GenFile = /*@__PURE__*/
  fileDesc("CgxiYXNhbHQucHJvdG8SBmJhc2FsdCIuCgxMb2dpblJlcXVlc3QSDAoEbmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIlCg1Mb2dpblJlc3BvbnNlEhQKDHNlc3Npb25Ub2tlbhgBIAEoCTI8CgRBdXRoEjQKBWxvZ2luEhQuYmFzYWx0LkxvZ2luUmVxdWVzdBoVLmJhc2FsdC5Mb2dpblJlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message basalt.LoginRequest
 */
export type LoginRequest = Message<"basalt.LoginRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message basalt.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_basalt, 0);

/**
 * @generated from message basalt.LoginResponse
 */
export type LoginResponse = Message<"basalt.LoginResponse"> & {
  /**
   * @generated from field: string sessionToken = 1;
   */
  sessionToken: string;
};

/**
 * Describes the message basalt.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_basalt, 1);

/**
 * @generated from service basalt.Auth
 */
export const Auth: GenService<{
  /**
   * @generated from rpc basalt.Auth.login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_basalt, 0);

